# FOR FRONT-END DEPLOYMENT... (REACT)
FROM node:16-alpine
WORKDIR /workdir
ENV PATH /workdir/app/node_modules/.bin:$PATH
COPY package.json ./
COPY postcss.config.js ./
COPY tailwind.config.js ./
COPY tsconfig.json ./
COPY next.config.js ./
COPY app ./app
WORKDIR /workdir/app
RUN npm install --force
RUN npm run build
EXPOSE 3000
CMD ["npm", "run", "start"]

# THIS IS CALLED MULTI-STAGE BUILDING IN DOCKER
# HOW TO PERSIST THE DATABASE.DB WHEN DOCKER BUILDING...
# https://docs.docker.com/get-started/05_persisting_data/
# FOR CAPROVER... https://caprover.com/docs/persistent-apps.html